// database/languageData.js - Comprehensive language list with greetings

export const COMPREHENSIVE_LANGUAGES = [
	// Featured languages (is_featured = true, with greetings)
	{ code: "es", name: "Spanish", flag: "🇪🇸", greeting: "¡Hola!", is_featured: true, display_order: 1 },
	{ code: "fr", name: "French", flag: "🇫🇷", greeting: "Bonjour!", is_featured: true, display_order: 2 },
	{ code: "de", name: "German", flag: "🇩🇪", greeting: "Hallo!", is_featured: true, display_order: 3 },
	{ code: "it", name: "Italian", flag: "🇮🇹", greeting: "Ciao!", is_featured: true, display_order: 4 },
	{ code: "pt", name: "Portuguese", flag: "🇵🇹", greeting: "Olá!", is_featured: true, display_order: 5 },
	{ code: "zh", name: "Mandarin Chinese", flag: "🇨🇳", greeting: "你好!", is_featured: true, display_order: 6 },
	{ code: "ja", name: "Japanese", flag: "🇯🇵", greeting: "こんにちは!", is_featured: true, display_order: 7 },
	{ code: "ko", name: "Korean", flag: "🇰🇷", greeting: "안녕하세요!", is_featured: true, display_order: 8 },
	{ code: "ar", name: "Arabic", flag: "🇸🇦", greeting: "مرحبا!", is_featured: true, display_order: 9 },
	{ code: "ru", name: "Russian", flag: "🇷🇺", greeting: "Привет!", is_featured: true, display_order: 10 },
	{ code: "hi", name: "Hindi", flag: "🇮🇳", greeting: "नमस्ते!", is_featured: true, display_order: 11 },
	{ code: "en", name: "English", flag: "🇬🇧", greeting: "Hello!", is_featured: true, display_order: 12 },

	// All other languages (alphabetically, is_featured = false, greeting = null)
	{ code: "af", name: "Afrikaans", flag: "🇿🇦", greeting: null, is_featured: false },
	{ code: "sq", name: "Albanian", flag: "🇦🇱", greeting: null, is_featured: false },
	{ code: "am", name: "Amharic", flag: "🇪🇹", greeting: null, is_featured: false },
	{ code: "hy", name: "Armenian", flag: "🇦🇲", greeting: null, is_featured: false },
	{ code: "az", name: "Azerbaijani", flag: "🇦🇿", greeting: null, is_featured: false },
	{ code: "eu", name: "Basque", flag: "🇪🇸", greeting: null, is_featured: false },
	{ code: "be", name: "Belarusian", flag: "🇧🇾", greeting: null, is_featured: false },
	{ code: "bn", name: "Bengali", flag: "🇧🇩", greeting: null, is_featured: false },
	{ code: "bs", name: "Bosnian", flag: "🇧🇦", greeting: null, is_featured: false },
	{ code: "bg", name: "Bulgarian", flag: "🇧🇬", greeting: null, is_featured: false },
	{ code: "my", name: "Burmese", flag: "🇲🇲", greeting: null, is_featured: false },
	{ code: "ca", name: "Catalan", flag: "🇪🇸", greeting: null, is_featured: false },
	{ code: "ceb", name: "Cebuano", flag: "🇵🇭", greeting: null, is_featured: false },
	{ code: "ny", name: "Chichewa", flag: "🇲🇼", greeting: null, is_featured: false },
	{ code: "co", name: "Corsican", flag: "🇫🇷", greeting: null, is_featured: false },
	{ code: "hr", name: "Croatian", flag: "🇭🇷", greeting: null, is_featured: false },
	{ code: "cs", name: "Czech", flag: "🇨🇿", greeting: null, is_featured: false },
	{ code: "da", name: "Danish", flag: "🇩🇰", greeting: null, is_featured: false },
	{ code: "nl", name: "Dutch", flag: "🇳🇱", greeting: null, is_featured: false },
	{ code: "eo", name: "Esperanto", flag: "🌍", greeting: null, is_featured: false },
	{ code: "et", name: "Estonian", flag: "🇪🇪", greeting: null, is_featured: false },
	{ code: "tl", name: "Filipino", flag: "🇵🇭", greeting: null, is_featured: false },
	{ code: "fi", name: "Finnish", flag: "🇫🇮", greeting: null, is_featured: false },
	{ code: "fy", name: "Frisian", flag: "🇳🇱", greeting: null, is_featured: false },
	{ code: "gl", name: "Galician", flag: "🇪🇸", greeting: null, is_featured: false },
	{ code: "ka", name: "Georgian", flag: "🇬🇪", greeting: null, is_featured: false },
	{ code: "el", name: "Greek", flag: "🇬🇷", greeting: null, is_featured: false },
	{ code: "gu", name: "Gujarati", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "ht", name: "Haitian Creole", flag: "🇭🇹", greeting: null, is_featured: false },
	{ code: "ha", name: "Hausa", flag: "🇳🇬", greeting: null, is_featured: false },
	{ code: "haw", name: "Hawaiian", flag: "🇺🇸", greeting: null, is_featured: false },
	{ code: "iw", name: "Hebrew", flag: "🇮🇱", greeting: null, is_featured: false },
	{ code: "hmn", name: "Hmong", flag: "🇨🇳", greeting: null, is_featured: false },
	{ code: "hu", name: "Hungarian", flag: "🇭🇺", greeting: null, is_featured: false },
	{ code: "is", name: "Icelandic", flag: "🇮🇸", greeting: null, is_featured: false },
	{ code: "ig", name: "Igbo", flag: "🇳🇬", greeting: null, is_featured: false },
	{ code: "id", name: "Indonesian", flag: "🇮🇩", greeting: null, is_featured: false },
	{ code: "ga", name: "Irish", flag: "🇮🇪", greeting: null, is_featured: false },
	{ code: "jw", name: "Javanese", flag: "🇮🇩", greeting: null, is_featured: false },
	{ code: "kn", name: "Kannada", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "kk", name: "Kazakh", flag: "🇰🇿", greeting: null, is_featured: false },
	{ code: "km", name: "Khmer", flag: "🇰🇭", greeting: null, is_featured: false },
	{ code: "ku", name: "Kurdish", flag: "🇮🇶", greeting: null, is_featured: false },
	{ code: "ky", name: "Kyrgyz", flag: "🇰🇬", greeting: null, is_featured: false },
	{ code: "lo", name: "Lao", flag: "🇱🇦", greeting: null, is_featured: false },
	{ code: "la", name: "Latin", flag: "🏛️", greeting: null, is_featured: false },
	{ code: "lv", name: "Latvian", flag: "🇱🇻", greeting: null, is_featured: false },
	{ code: "lt", name: "Lithuanian", flag: "🇱🇹", greeting: null, is_featured: false },
	{ code: "lb", name: "Luxembourgish", flag: "🇱🇺", greeting: null, is_featured: false },
	{ code: "mk", name: "Macedonian", flag: "🇲🇰", greeting: null, is_featured: false },
	{ code: "mg", name: "Malagasy", flag: "🇲🇬", greeting: null, is_featured: false },
	{ code: "ms", name: "Malay", flag: "🇲🇾", greeting: null, is_featured: false },
	{ code: "ml", name: "Malayalam", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "mt", name: "Maltese", flag: "🇲🇹", greeting: null, is_featured: false },
	{ code: "mi", name: "Maori", flag: "🇳🇿", greeting: null, is_featured: false },
	{ code: "mr", name: "Marathi", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "mn", name: "Mongolian", flag: "🇲🇳", greeting: null, is_featured: false },
	{ code: "ne", name: "Nepali", flag: "🇳🇵", greeting: null, is_featured: false },
	{ code: "no", name: "Norwegian", flag: "🇳🇴", greeting: null, is_featured: false },
	{ code: "ps", name: "Pashto", flag: "🇦🇫", greeting: null, is_featured: false },
	{ code: "fa", name: "Persian", flag: "🇮🇷", greeting: null, is_featured: false },
	{ code: "pl", name: "Polish", flag: "🇵🇱", greeting: null, is_featured: false },
	{ code: "pa", name: "Punjabi", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "ro", name: "Romanian", flag: "🇷🇴", greeting: null, is_featured: false },
	{ code: "sm", name: "Samoan", flag: "🇼🇸", greeting: null, is_featured: false },
	{ code: "gd", name: "Scots Gaelic", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", greeting: null, is_featured: false },
	{ code: "sr", name: "Serbian", flag: "🇷🇸", greeting: null, is_featured: false },
	{ code: "st", name: "Sesotho", flag: "🇱🇸", greeting: null, is_featured: false },
	{ code: "sn", name: "Shona", flag: "🇿🇼", greeting: null, is_featured: false },
	{ code: "sd", name: "Sindhi", flag: "🇵🇰", greeting: null, is_featured: false },
	{ code: "si", name: "Sinhala", flag: "🇱🇰", greeting: null, is_featured: false },
	{ code: "sk", name: "Slovak", flag: "🇸🇰", greeting: null, is_featured: false },
	{ code: "sl", name: "Slovenian", flag: "🇸🇮", greeting: null, is_featured: false },
	{ code: "so", name: "Somali", flag: "🇸🇴", greeting: null, is_featured: false },
	{ code: "su", name: "Sundanese", flag: "🇮🇩", greeting: null, is_featured: false },
	{ code: "sw", name: "Swahili", flag: "🇰🇪", greeting: null, is_featured: false },
	{ code: "sv", name: "Swedish", flag: "🇸🇪", greeting: null, is_featured: false },
	{ code: "tg", name: "Tajik", flag: "🇹🇯", greeting: null, is_featured: false },
	{ code: "ta", name: "Tamil", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "te", name: "Telugu", flag: "🇮🇳", greeting: null, is_featured: false },
	{ code: "th", name: "Thai", flag: "🇹🇭", greeting: null, is_featured: false },
	{ code: "tr", name: "Turkish", flag: "🇹🇷", greeting: null, is_featured: false },
	{ code: "uk", name: "Ukrainian", flag: "🇺🇦", greeting: null, is_featured: false },
	{ code: "ur", name: "Urdu", flag: "🇵🇰", greeting: null, is_featured: false },
	{ code: "uz", name: "Uzbek", flag: "🇺🇿", greeting: null, is_featured: false },
	{ code: "vi", name: "Vietnamese", flag: "🇻🇳", greeting: null, is_featured: false },
	{ code: "cy", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", greeting: null, is_featured: false },
	{ code: "xh", name: "Xhosa", flag: "🇿🇦", greeting: null, is_featured: false },
	{ code: "yi", name: "Yiddish", flag: "🇮🇱", greeting: null, is_featured: false },
	{ code: "yo", name: "Yoruba", flag: "🇳🇬", greeting: null, is_featured: false },
	{ code: "zu", name: "Zulu", flag: "🇿🇦", greeting: null, is_featured: false },
];
